[package]
name = "stbhw"
version = "0.1.0"
edition = "2021"
authors = ["Ryan1729 <Ryan1729@gmail.com>"]
license = "LICENSE"

[lib]
path = "./src/stbhw.rs"

[dependencies]

[build-dependencies]
cc = "1.0"

[features]
unsynced-tests=[]