#!/bin/bash

# bindgen was installed by running:
# cargo install bindgen
# As of this writing there are additional requirements.
# See https://rust-lang.github.io/rust-bindgen/requirements.html

bindgen wrapper.h -o src/sys/bindings.rs \
--allowlist-function '^stbhw_.*'                           \
--allowlist-function '^xs_.*'                              \
--blocklist-type '^__.*'                                   \
--no-layout-tests 

# We use --no-layout-tests becasue that seems less bad than 
# adding `#![allow(deref_nullptr)]`
# See https://github.com/rust-lang/rust-bindgen/issues/1651