#!/bin/bash

# bindgen was installed by running:
# cargo install bindgen

bindgen stb_herringbone_wang_tile.h -o src/sys/bindings.rs \
--allowlist-function '^stbhw_.*'                           \
--no-layout-tests 

# We use --no-layout-tests becasue that seems less bad than 
# adding `#![allow(deref_nullptr)]`
# See https://github.com/rust-lang/rust-bindgen/issues/1651